### ISSUE TITLE
Make the project into a light-weight PWA

### ISSUE THREAD

**Issue by DesignrKnight** [opencodenitr/project-apollo#23]

**Comment by Vedant1202** [comment]
Hi, @DesignrKnight , Can I work on this?

**Comment by HunainHumail** [comment]
I would like to work on this issue :)

**Comment by DesignrKnight** [comment]
Wow, that is fantastic, we have two people excited about this. To resolve conflict, I'll assign this to @Vedant1202 

Hey @HunainHumail , we have another repo with the same issue, if you are willing, you can work on that. Repo is still under the process of adding tags for hackoberfest. Give us a little time
https://github.com/dscnitrourkela/project-huckleberry

Thanks again
